# Generated by Django 4.2.3 on 2023-07-29 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_spamlist_blockedlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoViewedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_viewed_list', to=settings.AUTH_USER_MODEL)),
                ('viewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
