# Generated by Django 4.2.3 on 2023-08-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
